export const endpoints = {
  health: '/health',
  apiRoot: '/api/v1',
  auth: {
    register: '/api/v1/auth/register',
    login: '/api/v1/auth/login',
    refresh: '/api/v1/auth/refresh',
    logout: '/api/v1/auth/logout',
    passwordResetRequest: '/api/v1/auth/password-reset/request',
    passwordResetConfirm: '/api/v1/auth/password-reset/confirm',
  },
  me: '/api/v1/users/me',
  quran: {
    surahs: '/api/v1/quran/surahs',
    surah: (number: number) => `/api/v1/quran/surahs/${number}`,
    search: '/api/v1/quran/search',
    reciters: '/api/v1/quran/reciters',
    audio: '/api/v1/quran/audio',
    progress: '/api/v1/quran/progress',
    bookmarks: '/api/v1/quran/bookmarks',
    bookmark: (id: string) => `/api/v1/quran/bookmarks/${id}`,
  },
  podcasts: {
    series: '/api/v1/podcasts/series',
    seriesDetail: (slug: string) => `/api/v1/podcasts/series/${slug}`,
    episode: (id: string) => `/api/v1/podcasts/episodes/${id}`,
    progress: '/api/v1/podcasts/progress',
    favorites: '/api/v1/podcasts/favorites',
    favorite: (id: string) => `/api/v1/podcasts/favorites/${id}`,
  },
  videos: {
    series: '/api/v1/videos/series',
    seriesDetail: (slug: string) => `/api/v1/videos/series/${slug}`,
    episode: (id: string) => `/api/v1/videos/episodes/${id}`,
  },
  books: {
    list: '/api/v1/books',
    detail: (slug: string) => `/api/v1/books/${slug}`,
    chapter: (slug: string, chapterSlug: string) =>
      `/api/v1/books/${slug}/chapters/${chapterSlug}`,
    progress: '/api/v1/books/progress',
    bookmarks: '/api/v1/books/bookmarks',
    bookmark: (id: string) => `/api/v1/books/bookmarks/${id}`,
    highlights: '/api/v1/books/highlights',
    highlight: (id: string) => `/api/v1/books/highlights/${id}`,
  },
  research: {
    list: '/api/v1/research',
    detail: (slug: string) => `/api/v1/research/${slug}`,
    bookmarks: '/api/v1/research/bookmarks',
    bookmark: (id: string) => `/api/v1/research/bookmarks/${id}`,
  },
  curriculum: {
    paths: '/api/v1/curriculum/paths',
    path: (slug: string) => `/api/v1/curriculum/paths/${slug}`,
    progress: '/api/v1/curriculum/progress',
  },
  library: {
    continue: '/api/v1/library/continue',
    favorites: '/api/v1/library/favorites',
    bookmarks: '/api/v1/library/bookmarks',
  },
  search: '/api/v1/search',
  admin: {
    research: {
      list: '/api/v1/admin/research',
      item: (id: string) => `/api/v1/admin/research/${id}`,
      publish: (id: string) => `/api/v1/admin/research/${id}/publish`,
      status: (id: string) => `/api/v1/admin/research/${id}/status`,
    },
    curriculum: {
      list: '/api/v1/admin/curriculum',
      item: (id: string) => `/api/v1/admin/curriculum/${id}`,
      publish: (id: string) => `/api/v1/admin/curriculum/${id}/publish`,
      status: (id: string) => `/api/v1/admin/curriculum/${id}/status`,
    },
    podcasts: {
      series: '/api/v1/admin/podcasts/series',
      itemSeries: (id: string) => `/api/v1/admin/podcasts/series/${id}`,
      publishSeries: (id: string) => `/api/v1/admin/podcasts/series/${id}/publish`,
      statusSeries: (id: string) => `/api/v1/admin/podcasts/series/${id}/status`,
      seriesEpisodes: (id: string) => `/api/v1/admin/podcasts/series/${id}/episodes`,
      episodes: '/api/v1/admin/podcasts/episodes',
      episode: (id: string) => `/api/v1/admin/podcasts/episodes/${id}`,
      publishEpisode: (id: string) => `/api/v1/admin/podcasts/episodes/${id}/publish`,
    },
    videos: {
      series: '/api/v1/admin/videos/series',
      itemSeries: (id: string) => `/api/v1/admin/videos/series/${id}`,
      publishSeries: (id: string) => `/api/v1/admin/videos/series/${id}/publish`,
      statusSeries: (id: string) => `/api/v1/admin/videos/series/${id}/status`,
      seriesEpisodes: (id: string) => `/api/v1/admin/videos/series/${id}/episodes`,
      episodes: '/api/v1/admin/videos/episodes',
      episode: (id: string) => `/api/v1/admin/videos/episodes/${id}`,
      publishEpisode: (id: string) => `/api/v1/admin/videos/episodes/${id}/publish`,
    },
    books: {
      list: '/api/v1/admin/books',
      item: (id: string) => `/api/v1/admin/books/${id}`,
      publish: (id: string) => `/api/v1/admin/books/${id}/publish`,
      status: (id: string) => `/api/v1/admin/books/${id}/status`,
      bookChapters: (id: string) => `/api/v1/admin/books/${id}/chapters`,
      chapters: '/api/v1/admin/books/chapters',
      chapter: (id: string) => `/api/v1/admin/books/chapters/${id}`,
      publishChapter: (id: string) => `/api/v1/admin/books/chapters/${id}/publish`,
    },
    users: {
      list: '/api/v1/admin/users',
      role: (id: string) => `/api/v1/admin/users/${id}/role`,
      status: (id: string) => `/api/v1/admin/users/${id}/status`,
    },
  },
} as const;
